### ISSUE TITLE
Pd Vanilla standard external not working

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#56] opened 2015-12-20 15:22 UTC
After libPd migration #11, externals like expr~ are not correctly loaded.

.so files are presents in PdCore libs folder but there's errors on logcat output saying these can't be resolved.

This issue might be linked to pd-for-android issue : 
- https://github.com/libpd/pd-for-android/issues/32
- https://github.com/libpd/pd-for-android/issues/30

**Comment by mgsx-dev** [comment] 2015-12-20 16:10
I've write a test case with all vanilla extra : 
- all so files from PdCore are correctly loaded (bonk~, choice, expr, expr~, fexpr~, fiddle~, loop~, lrshift~, pique, sigmund~)
- all extra abstractions are correcly loaded (hilbert~, complex-mod~ and all reverbs rev1~, rev2~ ...etc)
- some extra are not included in PdCore (bob~, pd~ and stdout) but maybe these not part of libpd version

**Comment by mgsx-dev** [comment] 2015-12-20 16:14
I've test AcidDrum as well and nothing wrong with the snare, il have this in the logcat :

```
12-20 17:11:18.763: I/opensl_stream(8242): Starting player queue.
12-20 17:11:18.763: I/Pd [print](8242): expr, expr~, fexpr~ version 0.4 under GNU Lesser General Public License 
12-20 17:11:18.763: I/Pd [print](8242):  loadsave pattern
12-20 17:11:18.763: I/Pd [print](8242): error: ... couldn't create
12-20 17:11:18.763: I/Pd [print](8242):  loadsave synth
12-20 17:11:18.763: I/Pd [print](8242): error: ... couldn't create
```

So all is ok for me. But as mentionned in pd-for-android issues, this might be a Android version or Device specific bug ?

**Comment by b2renger** [comment] 2015-12-20 17:15
On Nexus 9 running 5.1.1, the test case gives me this in the logcat :

```
12-20 18:12:36.979: I/Pd [print](3371):  expr~ $1 +2
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  bob~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  bonk~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  choice
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  fiddle~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  loop~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  lrshift~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  pan~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  pd~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  pique
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  sigmund~
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
12-20 18:12:36.979: I/Pd [print](3371):  stdout
12-20 18:12:36.979: I/Pd [print](3371): error: ... couldn't create
```

**Comment by b2renger** [comment] 2015-12-20 18:46
On Nexus 5 running 6.0.1, I got this : 

```
12-20 19:44:24.087: I/Pd [print](30282): expr, expr~, fexpr~ version 0.4 under GNU Lesser General Public License 
12-20 19:44:24.087: I/Pd [print](30282):  bob~
12-20 19:44:24.087: I/Pd [print](30282): error: ... couldn't create
12-20 19:44:24.087: I/Pd [print](30282): bonk version 1.5
12-20 19:44:24.087: I/Pd [print](30282): fiddle version 1.1 TEST4
12-20 19:44:24.087: I/Pd [print](30282):  pan~
12-20 19:44:24.087: I/Pd [print](30282): error: ... couldn't create
12-20 19:44:24.087: I/Pd [print](30282):  pd~
12-20 19:44:24.088: I/Pd [print](30282): error: ... couldn't create
12-20 19:44:24.088: I/Pd [print](30282): pique 0.1 for PD version 23
12-20 19:44:24.088: I/Pd [print](30282): sigmund~ version 0.07
12-20 19:44:24.088: I/Pd [print](30282):  stdout
12-20 19:44:24.088: I/Pd [print](30282): error: ... couldn't create
```

so expr~ seems to work fine here aswell as a few others.

**Comment by b2renger** [comment] 2015-12-20 18:49
As a result aciddrums works fine on Nexus 5 running 6.0.1 and fails on Nexus 9 running 5.1.1.

After a quick check Nexus 9 has an arm64 cpu whereas Nexus 5 and arm cpu.

**Comment by mgsx-dev** [comment] 2015-12-21 12:16
I commited a temporary workaround : arm64-v8a are removed during the eclipse setup script. We could revert this changes when pd-for-android issue will be fixed.

**Comment by tkirshboim** [comment] 2015-12-21 22:12
Hi there! The issue is fixed on the master branch of pd-for-android. Hope it solves the issue for you. :pray:

**Closed as completed** 2015-12-22 21:01 UTC
Labels: bug

**Comment by mgsx-dev** [comment] 2015-12-22 21:03
@tkirshboim Thanks for your reactivity ! It solve the issue.

**Comment by redbeardanil** [comment] 2016-01-08 17:16
Vvyvvvvuggvuvvuuvgvguvvvvgv cu vuguvu cu gvvgvv uc uuvvvuv gu vv uc uuvvvuu gu uyu yufka fb Vvyvvvvuggvuvvuuvgvguvvvvgv g Ü de zaten sıkıntı var vvv cv v unity unreal enginede
